language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
env:
  matrix:
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=2.2

before_install:
  - curl http://sphinxsearch.com/files/sphinx-3.1.1-612d99f-linux-amd64-glibc2.12.tar.gz > sphinx-3.1.1.tar.gz
  - tar xzf sphinx-3.1.1.tar.gz


install:
  - pip install Django~=$DJANGO
  - pip install -r test-requires.txt
  - pip install codecov

# command to run tests
script:
    - mkdir sphinxdata/indexes -p
    - sphinx-3.1.1/bin/searchd -c `pwd`/test_config/sphinx.conf
    - python -m coverage run ./manage.py test -v3

after_success: codecov
