version: "3.5"
services:
    sphinxsearch:
        image: macbre/sphinxsearch:3.1.1
        container_name: sphinxsearch
        ports:
            - "9307:9307"
        volumes:
            - "./test_config/:/opt/sphinx/conf/"
            - "./tmp/:/sphinxdata/indexes/"

    django:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django_sphinx
        command: python manage.py test -v 1 --noinput
        depends_on:
            - sphinxsearch
        volumes:
            - "./:/app"
        ports:
            - "8005:8005"
